# Generated by Django 3.0.6 on 2020-06-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200625_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.BooleanField(default=False),
        ),
    ]
