# Generated by Django 3.0.6 on 2020-06-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_comment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
